### ISSUE TITLE
[BUG] The Games section isnt loading!

### ISSUE THREAD

**Issue by ali-kingX** [Lazap-Development/lazap#69]
![Screenshot 2022-08-16 081008](https://user-images.githubusercontent.com/93087009/184876212-66831c4f-2fe1-4f2f-b933-8c8b3d8f7c4e.png)

I thought it is meant to load the games but it's just stuck!

**Comment by LogicApples** [comment]
Hello,

Can you send us the logs?
(ctrl+shift+i)

**Comment by ali-kingX** [comment]
path: C:\Users\ali\AppData\Roaming\com.lazap.config\storage/cache/user/pfp.png: The system cannot find the file specified. (os error 2)
app.2a24ae26.js:1 ERROR: The system was unable to find the specified registry key or value.
app.2a24ae26.js:1 TypeError: Cannot read properties of undefined (reading 'split')
    at c (app.2a24ae26.js:1:9217)
    at async Module.l (app.2a24ae26.js:1:8706)
    at async Promise.all (/index 2)
    at async Module.u (app.2a24ae26.js:1:16571)
    at async app.2a24ae26.js:1:1010
app.2a24ae26.js:1 ERROR: The system was unable to find the specified registry key or value.
app.2a24ae26.js:1 TypeError: Cannot read properties of undefined (reading 'split')
    at c (app.2a24ae26.js:1:9217)
    at async Module.l (app.2a24ae26.js:1:8706)
    at async Promise.all (/index 2)
    at async u (app.2a24ae26.js:1:16571)
    at async Module.p (app.2a24ae26.js:1:17873)
    at async app.2a24ae26.js:1:1125
app.2a24ae26.js:1 ERROR: The system was unable to find the specified registry key or value.
app.2a24ae26.js:1 TypeError: Cannot read properties of undefined (reading 'split')
    at c (app.2a24ae26.js:1:9217)
    at async Module.l (app.2a24ae26.js:1:8706)
    at async Promise.all (/index 2)
    at async u (app.2a24ae26.js:1:16571)
    at async Module.p (app.2a24ae26.js:1:17873)
    at async app.2a24ae26.js:1:1207
app.2a24ae26.js:1 ERROR: The system was unable to find the specified registry key or value.
app.2a24ae26.js:1 TypeError: Cannot read properties of undefined (reading 'split')
    at c (app.2a24ae26.js:1:9217)
    at async Module.l (app.2a24ae26.js:1:8706)
    at async Promise.all (/index 2)
    at async u (app.2a24ae26.js:1:16571)
    at async Module.p (app.2a24ae26.js:1:17873)
    at async app.2a24ae26.js:1:1281
app.2a24ae26.js:1 ERROR: The system was unable to find the specified registry key or value.
app.2a24ae26.js:1 TypeError: Cannot read properties of undefined (reading 'split')
    at c (app.2a24ae26.js:1:9217)
    at async Module.l (app.2a24ae26.js:1:8706)
    at async Promise.all (/index 2)
    at async u (app.2a24ae26.js:1:16571)
    at async Module.p (app.2a24ae26.js:1:17873)
    at async app.2a24ae26.js:1:1350
app.2a24ae26.js:1 ERROR: The system was unable to find the specified registry key or value.
app.2a24ae26.js:1 TypeError: Cannot read properties of undefined (reading 'split')
    at c (app.2a24ae26.js:1:9217)
    at async Module.l (app.2a24ae26.js:1:8706)
    at async Promise.all (/index 2)
    at async u (app.2a24ae26.js:1:16571)
    at async Module.p (app.2a24ae26.js:1:17873)
    at async HTMLDivElement.<anonymous> (app.2a24ae26.js:1:2201)
app.2a24ae26.js:1 ERROR: The system was unable to find the specified registry key or value.
app.2a24ae26.js:1 TypeError: Cannot read properties of undefined (reading 'split')
    at c (app.2a24ae26.js:1:9217)
    at async Module.l (app.2a24ae26.js:1:8706)
    at async Promise.all (/index 2)
    at async u (app.2a24ae26.js:1:16571)
    at async Module.p (app.2a24ae26.js:1:17873)
    at async HTMLDivElement.<anonymous> (app.2a24ae26.js:1:2535)

**Comment by LogicApples** [comment]
Is this from nightly branch?

**Comment by ali-kingX** [comment]
?

**Comment by LogicApples** [comment]
Hm it looks like it's a problem in the main branch. Which launchers do you have on your computer?

**Comment by ali-kingX** [comment]
minecraft launcher, roblox

**Comment by LegItMate** [comment]
Can you run these 2 commands in powershell and provide us the output? 

```sh
Reg query "HKEY_CLASSES_ROOT\Applications\MinecraftLauncher.exe\shell\open\command" /ve
```

```sh
Get-appxpackage Microsoft.4297127D64EC6
```

**Comment by ali-kingX** [comment]
PS C:\Users\ali> Reg query "HKEY_CLASSES_ROOT\Applications\MinecraftLauncher.exe\shell\open\command" /ve
ERROR: The system was unable to find the specified registry key or value.
PS C:\Users\ali> Get-appxpackage Microsoft.4297127D64EC6


Name              : Microsoft.4297127D64EC6
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.1.21.0
PackageFullName   : Microsoft.4297127D64EC6_1.1.21.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.4297127D64EC6_1.1.21.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.4297127D64EC6_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

**Comment by ali-kingX** [comment]
also im using the knew launcher

**Comment by LogicApples** [comment]
Hi.
A PR has been opened regarding this issue. Now we just have to wait and see if it gets merged.
Cheers!

**Comment by DashCruft** [comment]
@ali-kingX Thank you for filing a report. 

We took this issue into consideration and have fixed it. 
Please download the latest executable in the `0.5.1` release:
https://github.com/Lazap-Development/lazap/releases/tag/v0.5.1

If you still encounter any issues, feel free to file another issue. Feature Requests are also welcome :)
