### ISSUE TITLE
[BUG] Everything is empty stuck on loading symbol

### ISSUE THREAD

**Issue by jonkristian** [Lazap-Development/Lazap#94]
**Describe the bug**
Everything is empty and screen seems stuck on the loading animation.

**To Reproduce**
Downloaded 0.6.1 msi, I'm on windows 11.

**Expected behavior**
Stuff being loaded.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional information**
Here's output from console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at b.getGameElement (app.729d5091.js:1:33185)
    at b.createGameElement (app.729d5091.js:1:35628)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at Module.y (app.729d5091.js:1:28338)
    at async app.729d5091.js:1:1770
app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at b.createGameElement (app.729d5091.js:1:35772)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at Module.y (app.729d5091.js:1:28338)
    at async app.729d5091.js:1:1770
30app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertAdjacentElement')
    at b.createGameElement (app.729d5091.js:1:35794)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at Module.y (app.729d5091.js:1:28338)
    at async app.729d5091.js:1:1770
app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at Object.c (app.729d5091.js:1:36819)
app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at b.getGameElement (app.729d5091.js:1:33185)
    at b.createGameElement (app.729d5091.js:1:35628)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at Module.y (app.729d5091.js:1:28338)
    at async HTMLDivElement.<anonymous> (app.729d5091.js:1:3329)
app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at b.createGameElement (app.729d5091.js:1:35772)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at Module.y (app.729d5091.js:1:28338)
    at async HTMLDivElement.<anonymous> (app.729d5091.js:1:3329)
30app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertAdjacentElement')
    at b.createGameElement (app.729d5091.js:1:35794)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at Module.y (app.729d5091.js:1:28338)
    at async HTMLDivElement.<anonymous> (app.729d5091.js:1:3329)
app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at b.getGameElement (app.729d5091.js:1:33185)
    at b.createGameElement (app.729d5091.js:1:35628)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at y (app.729d5091.js:1:28338)
app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at b.createGameElement (app.729d5091.js:1:35772)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at y (app.729d5091.js:1:28338)
30app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertAdjacentElement')
    at b.createGameElement (app.729d5091.js:1:35794)
    at app.729d5091.js:1:28363
    at Array.forEach (<anonymous>)
    at y (app.729d5091.js:1:28338)
4app.729d5091.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at Object.c (app.729d5091.js:1:36819)
```

**Comment by p0ryae** [comment]
Hmm. The log could be more helpful. 

Do you have Steam or any launchers on your system at all?

**Comment by p0ryae** [comment]
Due to the inactivity and no response, I'm going to close this issue.

Feel free to reopen if you encounter issues with the latest release.
